CREATE TABLE dish
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(15)                             NOT NULL,
    price       INT                                     NOT NULL,
    description TEXT                                    NOT NULL,
    category_id BIGINT                                  NOT NULL,
    image_Url   TEXT                                    NOT NULL,
    CONSTRAINT FK_DISH_CATEGORY_ID FOREIGN KEY (category_id) REFERENCES category (id)
);
